### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by Floens** [Floens/uchan#1]
Roadmap

- [x] memcached caching
- [x] file uploading
- [x] bans and cooldowns
- [x] varnish
- [x] setup script
- [x] setup guide
- [x] additional post formatting options
- [ ] Database migrations with alembic
- [ ] Stickies
- [ ] Tripcodes (plugin?)
- [ ] API
- [ ] Tests
- [ ] Some javascript integration
- [ ] Plugin system
- [ ] Captchas plugin
- [ ] Word filter plugin
- [ ] WebM (plugin?)
